version: '3.3'
services:
  backend:
    image: nhadjarab/esgi-devops-repo:back
    environment:
      - REDIS_HOST=redis
    ports:
      - 8081:8081
    depends_on:
      - redis
    container_name: backend
  frontend:
    image: nhadjarab/esgi-devops-repo:front
    ports:
      - 80:80
    container_name: frontend
  redis:
    image: redis
    container_name: redis
